<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"><head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <link rel="icon" href="<?php echo C('f-img');?>/logo.ico" type="image/x-icon"/>
    <meta content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0" name="viewport">
    <title>深圳网站建设,深圳网站设计,深圳网页设计,响应式网站建设-深圳跃飞-获奖的深圳网站建设公司</title>
    <meta name="Keywords" content="深圳网站建设,深圳网站设计,深圳网页设计,响应式网站建设-深圳跃飞">
    <meta name="Description" content="深圳网站建设,深圳网站设计,深圳网页设计,响应式网站建设-深圳跃飞-获奖的深圳网站建设公司">

    <link rel="stylesheet" type="text/css" href="<?php echo C('f-css');?>/css.css">
<body style="background:#FFF;">
<div class="head">
    <a href="#" class="logo"><img src="<?php echo C('f-img');?>/logo.png"></a>
    <div class="nav">
        <?php foreach ($menu as $k=>$v):?>
            <a href="<?php echo U($v['url']);?>"><?php echo $v['text'];?></a>
        <?php endforeach;?>
    </div>
    <div class="phone"><b><img src="<?php echo C('f-img');?>/phone.png" alt="做网站:<?php echo C('Phone');?>"></b><span id="phone1"><?php echo C('Phone');?></span></div>

</div>
<div class="gywm_top">跃飞，不止是一家网站建设公司<span>我们信仰并一直坚持，为客户打造真正有价值的互联网平台</span></div>
<div class="gywm_ln">
    <div class="ln_r">
        <div class="span1">产品<br>能力积累</div>
        <div class="span2">研究<br>调研</div>
        <div class="span3">客户<br>需求</div>
    </div>
    <div class="ln_l">
        <h3>我们的理念</h3>
        <div class="txt">早在2009年，我们就开始设计网站。<br>8年来，深圳跃飞科技有限公司追求并一直坚持，为客户打造适合的真正有价值的互联网平台。 <br>认真聆听客户的思想，追求在战略理解上与客户同步；精心制定落地的计划，雕琢每一个面向用户的细节。 <br>我们对网站策划、用户体验与互动、视觉传达、前后台应用系统、国际化标准和流行趋势、进行不断的研究和实践，拥有丰富的经验和理念。</div>
    </div>
</div>
<div class="gywm_tu"></div>
<div class="warp gywm_warp">
    <ul>
        <li>
            <div class="tu">
                <img src="<?php echo C('f-img');?>/gywm_a1.png">
            </div>
            <h2>高端品牌网站定制</h2>
            <i>基于web的品牌表现</i>
            <i>社会化媒体整合</i>
            <i>品牌web视觉规范</i>
        </li>
        <li>
            <div class="tu">
                <img src="<?php echo C('f-img');?>/gywm_a2.png">
            </div>
            <h2>移动互联网解决方案</h2>
            <i>微信、APP、WAP网站</i>
            <i>响应式web设计</i>
        </li>
        <li>
            <div class="tu">
                <img src="<?php echo C('f-img');?>/gywm_a3.png">
            </div>
            <h2>复杂系统开发定制</h2>
            <i>拥有双软认证的CMS系统</i>
            <i>大型站群及定制电商平台开发</i>
        </li>
        <li class="li4">
            <div class="tu">
                <img src="<?php echo C('f-img');?>/gywm_a4.png">
            </div>
            <h2>用户体验优化</h2>
            <i>用户调研分析</i>
            <i>组织、流程、交互梳理</i>
            <i>UE、UI输出</i>
            <i>用户体验测试调研</i>
        </li>
    </ul>
</div>
<div class="gywm_san">
    <div class="san_c san_c1">
        <div class="san_t"></div>
        <div class="txt">早在2009年，我们就开始设计网站。8年来，我们追求并一直坚持，为客户打造适合的真正有价值的互联网平台。 </div>
    </div>
    <div class="san_c san_c2">
        <div class="san_t"></div>
        <div class="txt">近千项目经验，客户满意度是项目内审的唯一衡量标准。我们坚持以顾问的姿态，主动提供的专业建议。</div>
    </div>
    <div class="san_c san_c3">
        <div class="san_t"></div>
        <div class="txt">10多家世界五百强客户，成熟的客户督促我们成长。以全情的投入，达成严苛的标准。 </div>
    </div>
    <div class="clear"></div>
</div>
<div class="clear"></div>
<?php include "App/Home/View/Layout/footer.phtml";?>
</body>
</html>