<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<link rel="icon" href="<?php echo C('f-img');?>/logo.ico" type="image/x-icon"/>
	<meta content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0" name="viewport">
	<title>深圳网站建设,深圳网站设计,深圳网页设计,响应式网站建设-跃飞科技</title>
	<meta name="Keywords" content="深圳网站建设,深圳网站设计,深圳网页设计,响应式网站建设-深圳跃飞">
	<meta name="Description" content="深圳网站建设,深圳网站设计,深圳网页设计,响应式网站建设-深圳跃飞-获奖的深圳网站建设公司">

	<link rel="stylesheet" type="text/css" href="<?php echo C('f-css');?>/css.css">
	<link rel="stylesheet" href="<?php echo C('f-css');?>/responsiveslides.css">
	<link rel="stylesheet" href="<?php echo C('f-css');?>/banner.css">
	<script src="<?php echo C('f-js');?>/jquery-1.10.1.min.js"></script>
	<script src="<?php echo C('f-js');?>/responsiveslides.min.js"></script>
	<script>
		$(function () {
			$("#slider4").responsiveSlides({
				auto: true,
				pager: false,
				nav: true,
				speed: 500,
				namespace: "callbacks",
				before: function () {
				},
				after: function () {
				}
			});
		});
	</script>

</head>
<body>
<link rel="stylesheet" type="text/css" href="<?php echo C('f-css');?>/top_css.css">
<!--顶部-->
<div class="head">
	<a href="javascript:void(0);" class="logo"><img src="<?php echo C('f-img');?>/logo.png"></a>
	<div class="nav">
		<?php foreach ($menu as $k=>$v):?>
		<a href="<?php echo U($v['url']);?>"><?php echo $v['text'];?></a>
		<?php endforeach;?>
	</div>
	<div class="phone"><b><img src="<?php echo C('f-img');?>/phone.png" alt="#"></b><span id="phone1">18929329587</span></div>
</div>
<div class="callbacks_container">
	<ul class="rslides" id="slider4">
		<li>
			<a href="http://www.tomrepair.com" target="_blank"><img src="<?php echo C('f-img');?>/3.jpg" alt="TOMREPAIR"></a>
			<p class="caption">TOMREPAIR</p>
		</li>
		<li>
			<a href="http://www.geekvida.es" target="_blank"><img src="<?php echo C('f-img');?>/1.jpg" alt="GV西语站"></a>
			<p class="caption">GV西语站</p>
		</li>
		<li>
			<a href="http://www.geekvida.pt" target="_blank"><img src="<?php echo C('f-img');?>/2.jpg" alt="GV葡语站"></a>
			<p class="caption">GV葡语站</p>
		</li>
	</ul>
</div>

<!--四个圈-->
<h2 class="warp_h2">跃飞，不止是一家网站建设公司<span>我们信仰并一直坚持，为客户打造真正有价值的互联网平台</span><b>详情致电：<a href="javascript:void(0);" id="phone2">18929329587</a></b></h2>
<div class="warp">
	<ul>
		<li class="">
			<a>
				<div class="tu">
					<img src="<?php echo C('f-img');?>/103035690d561f3b8-c.jpg" alt="#">
					<div class="light"></div>
				</div>
				<h2>高端品牌网站定制</h2>
				<p>
					<i>基于web的品牌表现</i> <i>社会化媒体整合</i> <i>品牌web视觉规范</i></p>
			</a>
		</li><li class="">
			<a>
				<div class="tu">
					<img src="<?php echo C('f-img');?>/1030551997ad43bf9-6.jpg" alt="#">
					<div class="light"></div>
				</div>
				<h2>移动互联网解决方案</h2>
				<p>
					<i>微信、APP、WAP网站</i> <i>响应式web设计</i></p>
			</a>
		</li><li class="">
			<a>
				<div class="tu">
					<img src="<?php echo C('f-img');?>/1031593800f5386a-7.jpg" alt="#">
					<div class="light"></div>
				</div>
				<h2>复杂系统开发定制</h2>
				<p>
					<i>拥有双软认证的CMS系统</i> <i>大型站群及定制电商平台开发</i></p>
			</a>
		</li><li class="li4">
			<a>
				<div class="tu">
					<img src="<?php echo C('f-img');?>/103127334adab3be1-9.jpg" alt="#">
					<div class="light"></div>
				</div>
				<h2>用户体验优化</h2>
				<p>
					<i>用户调研分析</i> <i>组织、流程、交互梳理</i> <i>UE、UI输出</i> <i>用户体验测试调研</i></p>
			</a>
		</li>

	</ul>
</div>
<!--案例-->
<div class="warp_list" id="al">
	<ul class="list">
		<li>
			<a href="javascript:void(0);">
				<img class="tu" src="<?php echo C('f-img');?>/1039108518efa3059-2_Cut476421.jpg" alt="#">
				<div class="hg">
					<b><img src="<?php echo C('f-img');?>/143039420b8fdd58-e.png"></b>
					<div class="tet"><p>
							<i>用户体验优化UX/UI</i> <i>设计Design</i></p>
					</div></div>
			</a>
		</li>
		<li>
			<a href="javascript:void(0);">
				<img class="tu" src="<?php echo C('f-img');?>/105822935e744c775-b_Cut476421.jpg" alt="#">
				<div class="hg">
					<b><img src="<?php echo C('f-img');?>/10582759821dffaf3-e.png"></b>
					<div class="tet"><p>
							<i>策略Strategy</i> <i>原型UX/UI</i> <i>设计Design</i><i>开发Development</i></p>
					</div></div>
			</a>
		</li>
		<li>
			<a href="javascript:void(0);">
				<img class="tu" src="<?php echo C('f-img');?>/10591454ca83d5d8-6_Cut476421.jpg" alt="#">
				<div class="hg">
					<b><img src="<?php echo C('f-img');?>/105919198a5110b5-d.png"></b>
					<div class="tet"><p>
							<i>策略Strategy</i> <i>原型UX/UI</i> <i>设计Design</i><i>开发Development</i></p>
					</div></div>
			</a>
		</li>
		<li>
			<a href="javascript:void(0);">
				<img class="tu" src="<?php echo C('f-img');?>/111697193230b61-e_Cut476421.jpg" alt="#">
				<div class="hg">
					<b><img src="<?php echo C('f-img');?>/11110505b8349aaa-8.png"></b>
					<div class="tet"><p>
							<i>策略Strategy</i> <i>设计Design</i> <i>视差滚动Parallax Scrolling</i><i>开发Development</i></p>
					</div></div>
			</a>
		</li>
		<li class="li5">
			<a href="javascript:void(0);">
				<img class="tu" src="<?php echo C('f-img');?>/112579022b271637-d_Cut952421.jpg" alt="#">
				<div class="hg">
					<b><img src="<?php echo C('f-img');?>/1132782c2c272c1-a.png"></b>
					<div class="tet"><p>
							<i>策略Strategy</i> <i>原型UX/UI</i> <i>响应式设计Responsive Web Design</i><i>开发Development</i></p>
					</div></div>
			</a>
		</li>
		<li>
			<a href="javascript:void(0);">
				<img class="tu" src="<?php echo C('f-img');?>/11330359db777bff-7_Cut476421.jpg" alt="#">
				<div class="hg">
					<b><img src="<?php echo C('f-img');?>/11358429f0f4fba-b.png"></b>
					<div class="tet"><p>
							<i>原型UX/UI</i> <i>设计Design</i> <i>开发Development</i></p>
					</div></div>
			</a>
		</li>
		<li>
			<a href="javascript:void(0);">
				<img class="tu" src="<?php echo C('f-img');?>/1141456518acb31f-d_Cut476421.jpg" alt="#">
				<div class="hg">
					<b><img src="<?php echo C('f-img');?>/114319163bba7c5-9.png"></b>
					<div class="tet"><p>
							<i>原型UX/UI</i> <i>设计Design</i></p>
					</div></div>
			</a>
		</li>
		<li>
			<a href="javascript:void(0);">
				<img class="tu" src="<?php echo C('f-img');?>/1158801f29b0820-4_Cut476421.jpg" alt="#">
				<div class="hg">
					<b><img src="<?php echo C('f-img');?>/11513158b354398e-2.png"></b>
					<div class="tet"><p>
							<i>策略Strategy</i> <i>原型UX/UI</i> <i>设计Design</i><i>开发Development</i></p>
					</div></div>
			</a>
		</li>
		<li>
			<a href="javascript:void(0);">
				<img class="tu" src="<?php echo C('f-img');?>/11540893d860bf7f-4_Cut476421.jpg" alt="#">
				<div class="hg">
					<b><img src="<?php echo C('f-img');?>/11546194bab52937-3.png"></b>
					<div class="tet"><p>
							<i>策略Strategy</i> <i>原型UX/UI</i> <i>响应式设计Responsive Web Design</i><i>视频化背景 Video Background</i><i>开发Development</i></p>
					</div></div>
			</a>
		</li>
		<li>
			<a href="javascript:void(0);">
				<img class="tu" src="<?php echo C('f-img');?>/11621496d1c78d52-0_Cut476421.jpg" alt="#">
				<div class="hg">
					<b><img src="<?php echo C('f-img');?>/11624874d657a034-a.png"></b>
					<div class="tet"><p>
							<i>策略Strategy</i> <i>原型UX/UI</i> <i>设计Design</i><i>开发Development</i></p>
					</div></div>
			</a>
		</li>
		<li>
			<a href="javascript:void(0);">
				<img class="tu" src="<?php echo C('f-img');?>/11650381123f908c-4_Cut476421.jpg" alt="#">
				<div class="hg">
					<b><img src="<?php echo C('f-img');?>/1165768402b629f1-d.png"></b>
					<div class="tet"><p>
							<i>策略Strategy</i> <i>原型UX/UI</i> <i>响应式设计Responsive Web Design</i><i>开发Development</i></p>
					</div></div>
			</a>
		</li>
	</ul>
</div>
<div class="clear"></div>
<!--案例LOGO-->
<div class="list_logo">
	<div class="tet">
		<div class="warp_tet">
			<div class="clear"></div>
			<b><img src="<?php echo C('f-img');?>/1046427223a4ee80d-2.jpg" alt="#"><a class="a1"></a><a class="a2"></a><a class="a3"></a></b><p>
				早在2009年，我们就开始设计网站。8年来，我们追求并一直坚持，为客户打造适合的真正有价值的互联网平台。
				认真聆听客户的思想，追求在战略理解上与客户同步；精心制定落地的计划，雕琢每一个面向用户的细节。
				我们对网站策划、用户体验与互动、视觉传达、前后台应用系统、国际化标准和流行趋势、进行不断的研究和实践，拥有丰富的经验和理念。</p>
		</div>
	</div>

<!--	合作客户公司网站logo-->
	<ul>
		<?php foreach ($smallLogo as $k=>$v):?>
		<li>
			<div class="tu">
				<table width="100%" height="100%" border="0" cellspacing="0" cellpadding="0">
					<tbody>
					<tr>
						<td align="center" valign="middle"><img src="<?php echo C('f-img');?>/<?php echo $v;?>" alt="网站公司" /></td>
					</tr>
					</tbody>
				</table>
			</div>
		</li>
	<?php endforeach;?>
	</ul>

</div>
<?php include "App/Home/View/Layout/footer.phtml";?>
</body>
</html>